### PR TITLE
Adds FORCE_SSL constant to Omeka_Storage_Adapter_ZendS3

### PR DESCRIPTION
**Pull request by ebellempire**
See conversation at https://forum.omeka.org/t/amazon-s3-via-https/7742

### CODE REVIEW

**Comment by ebellempire** [comment]
Should I resubmit this with an @ to suppress the `undefined index` warning in the automated tests?

$force_ssl = (bool) @$this->_options[self::FORCE_SSL];

**Comment by ebellempire** [comment]
Will resubmit, thanks!

**Comment by zerocrates** [comment]
One more thought: since you're doing the comparatively more expensive `parse_url` there maybe it's better to do that calculation in the constructor so it only happens once regardless of how many URLs are generated... so you'd just create the base URL once and save it in a property that would get used in getUri().

It's not terribly significant but there's really no reason to re-do the operation for every URL.

**Comment by ebellempire** [comment]
Resubmitted: https://github.com/omeka/Omeka/pull/876

**Pull request closed without merging**
