### PR TITLE
Standardize drawer function for consistency and accessibility

### PR DESCRIPTION
**Pull request by kimisgold**
This pull request consolidates multiple uses of the "drawer" pattern where a component can collapse and expand, and often be marked for removal or be dragged to create order. It also does the following:

* Many interactive elements are now buttons, where they had been previously anchors or divs.
* Buttons and other form elements now have descriptive aria-labels and titles.
* There are now screen reader alerts for when new drawers have been added to the drawer list.
* There is now `Omeka.manageDrawers()` in `globals.js`, to centralize near identical functionality spread across js for navigation and item type elements.

### CODE REVIEW

**Comment by kimisgold** [comment]
I'll bump this for review since we're amidst a bunch of accessibility work anyway. I've updated the branch with changes from master and to also include "No description available" text for elements that have not been provided a description, which I think was the last todo on the [testing issue](https://github.com/omeka/Omeka/issues/997).

**Comment by zerocrates** [comment]
Some sort of problem has happened with the merge or rebase here.

**Comment by kimisgold** [comment]
The `style.css.map` was flagged for almost every commit. I tried to recompile and add it each time, but maybe that was not the move.

**Comment by zerocrates** [comment]
It's not so much that but more the... directionality of the rebase or whatever happened here. I'll see what I can do about it.

**Comment by zerocrates** [comment]
Take a look at https://github.com/omeka/Omeka/compare/master...drawer-toggle-a11y-rebase and see if it has everything you want it to have from this branch.

**Comment by kimisgold** [comment]
> Take a look at [master...drawer-toggle-a11y-rebase](https://github.com/omeka/Omeka/compare/master...drawer-toggle-a11y-rebase) and see if it has everything you want it to have from this branch.

It looks good to me.

**Pull request closed without merging**
