### PR TITLE
Explain more, which pages/places are affected

### PR DESCRIPTION
**Pull request by luku**
Hi, feel free to correct the texts, I don't know if *show pages* is really in English, but you can see the point

### CODE REVIEW

**Comment by zerocrates** [comment]
I think "show pages" is perfectly legit here.

**Comment by zerocrates** [comment]
@mebrett @kimisgold happiness with these changes? (adding the description "Include empty elements in show pages." to Show Empty Elements and "Include element set headings in show pages and in drop-down lists." to Show Element Set Headings in Appearance Settings?

We can tweak the language and/or align with the documentation if necessary. I do believe these are accurate, i.e. that they don't affect anywhere outside of the mentioned locations.

**Comment by kimisgold** [comment]
This all makes sense to me.

**Comment by mebrett** [comment]
Ditto.

**Comment by zerocrates** [comment]
Really should have merged this one a long time ago... let's not look at the dates involved.

**Pull request merged**
